<?php /** @var $viewModel T4webEmployees\Controller\User\ListViewModel */ ?>
<?php $viewModel = $this->viewModel()->getCurrent();?>

<!-- Modal -->
<div id="salary-modal" class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">Г—</button>
                <h4 class="modal-title" id="myModalLabel">Change Salary</h4>
            </div>

            <div class="modal-body">
                <form class="panel form-horizontal" action="#">
                    <input name="id" type="hidden" value="">
                    <input name="employeeId" type="hidden" value="">
                    <input name="date" type="hidden" value="">

                    <div class="panel-body">
                        <div class="row">
                            <div class="col-md-6">
                                <input type="text" class="form-control form-group-margin" placeholder="Amount" name="amount">
                            </div>
                            <div class="col-md-5">
                                <select class="form-control form-group-margin" name="currency">
                                    <?php foreach($viewModel->getCurrencies() as $code => $currency): ?>
                                        <option value="<?= $code; ?>"><?= $currency; ?></option>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                        </div><!-- row -->
                        <textarea placeholder="Comment" rows="4" class="form-control form-group-margin" name="comment"></textarea>
                    </div>
                </form>
            </div> <!-- / .modal-body -->

            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div> <!-- / .modal-content -->
    </div> <!-- / .modal-dialog -->
</div> <!-- /.modal -->
<!-- / Modal -->