<div class="page-header">
    <div class="row">
        <h1 class="col-sm-4 text-center text-left-sm col-xs-12">
            <i class="fa fa-users page-header-icon"></i>&nbsp;&nbsp;<a href="/employees">Emploees</a>&nbsp;&nbsp;<i class="fa fa-angle-right page-header-icon"></i>&nbsp;&nbsp;Robert Jang
        </h1>
    </div>
</div>

<div class="row">
    <div class="col-lg-5 col-md-5 col-sm-5 col-xs-12">
        <!-- col-lg-4 start here -->
        <div class="panel panel-danger panel-dark widget-profile">
            <div class="panel-heading">
                <div class="widget-profile-bg-icon"><i class="fa fa-bug"></i></div>
                <img class="widget-profile-avatar" alt="" src="/assets/demo/avatars/1.jpg">
                <div class="widget-profile-header">
                    <span class="text-bold">Robert Jang</span>
                </div>
            </div> <!-- / .panel-heading -->
            <div class="panel-body">
                Other info
            </div>
            <div class="list-group">
                <span class="list-group-item"><i class="fa fa-puzzle-piece list-group-icon"></i>Quality assurance engineer</span>
                <span class="list-group-item"><i class="fa fa-phone list-group-icon"></i>097-913-22-55</span>
                <span class="list-group-item"><i class="fa fa-skype list-group-icon"></i>fedot.kuzyakin</span>
                <span class="list-group-item"><i class="fa fa-envelope-o list-group-icon"></i>kuzya@t4web.com.ua</span>
                <a class="list-group-item" href="https://www.facebook.com/fedot" target="_blank"><i class="fa fa-facebook-square list-group-icon"></i>facebook.com/fedot</a>
            </div>
        </div>
        <!-- End .panel -->
    </div>
    <!-- col-lg-4 end here -->
    <div class="col-lg-7 col-md-7 col-sm-7 col-xs-12">
        <!-- col-lg-4 start here -->
        <div class="panel panel-default plain">
            <!-- Start .panel -->
            <div class="panel-heading">
                <h4 class="panel-title">Update info</h4>
            </div>
            <div class="panel-body">
                <form role="form" class="form-vertical">
                    <div class="form-group">
                        <label class="control-label">Username</label>
                        <input type="text" value="SuggeElson" class="form-control">
                    </div>
                    <div class="form-group">
                        <label class="control-label">Full name</label>
                        <input type="text" value="Jonh Doe" class="form-control">
                    </div>
                    <div class="form-group">
                        <label class="control-label">Email</label>
                        <input type="email" value="suggeelson@suggeelson.com" class="form-control">
                    </div>
                    <div class="form-group">
                        <label class="control-label">New password</label>
                        <input type="password" class="form-control">
                    </div>
                    <div class="form-group">
                        <label class="control-label">Repeat password</label>
                        <input type="password" class="form-control">
                    </div>
                    <div class="form-group">
                        <label class="control-label">More info</label>
                        <textarea rows="3" class="form-control"></textarea>
                    </div>
                    <!-- End .form-group  -->
                    <div class="form-group mb15">
                        <button class="btn btn-primary">Save</button>
                    </div>
                    <!-- End .form-group  -->
                </form>
            </div>
        </div>
        <!-- End .panel -->
    </div>
    <!-- col-lg-4 end here -->
</div>